[versions]
agp = "8.13.2"
kotlin = "2.2.21"
junit = "4.13.2"
hilt = "2.57.2"
retrofit = "2.11.0"
kotlinx-coroutines = "1.10.2"
okhttp = "4.12.0"
coil = "2.7.0"
gson = "2.13.2"

[libraries]
catalog = { group = "com.jacknic.android.wanandroid", name = "catalog", version = "0.0.1" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = 'com.squareup.retrofit2:converter-gson', version.ref = 'retrofit' }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { module = 'com.google.code.gson:gson', version.ref = 'gson' }

timber = 'com.jakewharton.timber:timber:5.0.1'
logger = 'com.orhanobut:logger:2.2.0'

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
lottie-compose = "com.airbnb.android:lottie-compose:6.7.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }